version: '3'
services:
  discovery:
    image: docker.kapusnik.cz/nsd:python
    build: nsd/
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PORT=8554
      - NAME=Nanny
#    ports:
#      - 53:53
#      - 53:53/udp

  ir:
    image: docker.kapusnik.cz/ir
    build: ir/
    restart: unless-stopped
    volumes:
      - /dev/gpiomem:/dev/gpiomem
    environment:
      - PORT=4000
    ports:
      - "4000:4000"

  nginx:
    image: nginx:latest
    volumes:
      - ./api.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"