version: '3'
services:
  discovery:
    image: docker.kapusnik.cz/nsd
    network_mode: host
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PORT=8554
      - NAME=Nanny
#    ports:
#      - 53:53
#      - 53:53/udp

  ir:
    image: docker.kapusnik.cz/ir
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/mem:/dev/mem
    environment:
      - PORT=4000
    ports:
      - "4000:4000"

  wifi:
    image: docker.kapusnik.cz/wifi
    restart: unless-stopped
    privileged: true
    volumes:
      - /proc/net/wireless:/signal
    ports:
      - "5000:8080"

  nginx:
    image: nginx:alpine
    volumes:
      - ./api.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"